### ISSUE TITLE
Invalid Owner Reserve

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#600]
If there are two or less objects subject to Owner Reserve, the Owner Reserve required by the RippleState object is 0XRP.

Total Reserved in this case should be 10XRP.
https://testnet.xrpl.org/accounts/rJzJwydbzVLqJSgLW99T7auNo7Wuy8aNgu

**Comment by ckniffen** [comment]
After some investigation we are going to keep it as is.  The rational for this is only trust lines are affected by this condition.  As such saying this account has a reserve of 14 is correct.  In order for a new object to be added the account will need 14 + incremental reserve.

For example in order to mint an NFT on that account you need 16(14 + 2) XRP and not 12.9 (10.9 + 2).

One option is to update the text to something other than "Reserve".  Maybe "Reserve Requirement"
