### ISSUE TITLE
 XRPL's testnet explorer, add token list

### ISSUE THREAD

**Issue by wojake** [ripple/explorer#74]
Could you guys add a list of tokens on the testnet page? There's a list of tokens on the mainnet [page](https://mainnet.xrpl.org/tokens).

This would be beneficial to devs who want to add random trustlines and start issuing DeX Offers from there on, https://github.com/XRPLF/xrpl-dev-portal/issues/1185 would also benefit from this.

**Comment by mvadari** [comment]
There is no token list on the testnet network because we don't have the same data for testnet - our data source is [a BigQuery database](https://github.com/WietseWind/fetch-xrpl-transactions) that only has data from mainnet. 

If you want to experiment with trustlines and DEX offers on the testnet, you can do that yourself pretty easily, with an issuer account and a couple of user accounts.
